[project]
name = "taskflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TheTarnished", email = "ali.jadidian.ai@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
    "django-filter>=26.1",
    "django-redis>=7.0.0",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.3",
    "redis>=8.1.0",
]

[project.scripts]
taskflow = "taskflow:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
]
